# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20160511_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('it_code', models.CharField(max_length=20, unique=True, verbose_name=b'\xe8\xb4\xa6\xe5\x8f\xb7')),
                ('phone', models.CharField(max_length=20, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe7\x94\xb5\xe8\xaf\x9d')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.IndustryGroup')),
            ],
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name=b'IDC\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'verbose_name': 'IDC',
                'verbose_name_plural': 'IDC',
            },
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='maintenance_group',
            new_name='maintenance_name',
        ),
        migrations.RenameField(
            model_name='networkdevice',
            old_name='power',
            new_name='powers',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='power_num',
            new_name='powers',
        ),
        migrations.RemoveField(
            model_name='host',
            name='maintenance_date',
        ),
        migrations.RemoveField(
            model_name='host',
            name='maintenance_group_name',
        ),
        migrations.RemoveField(
            model_name='host',
            name='product_model',
        ),
        migrations.RemoveField(
            model_name='host',
            name='sys_admin_contact',
        ),
        migrations.RemoveField(
            model_name='host',
            name='sys_admin_mail',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='entrance_date',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='entrance_mail',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='entrance_peo',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='entrance_phone',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='local_admin_contact',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='local_admin_mail',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='maintenance_date',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='out_date',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='out_mail',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='out_peo',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='out_phone',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='out_reason',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='product_model',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='sys_admin_contact',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='sys_admin_mail',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='maintenance_date',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='manufacturers',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='product_model',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='state',
        ),
        migrations.AddField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(null=True, unique=True, verbose_name=b'IP\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AddField(
            model_name='host',
            name='maintenance_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Maintenance', to_field=b'maintenance_name', verbose_name=b'\xe7\xbb\xb4\xe4\xbf\x9d\xe5\x8d\x95\xe4\xbd\x8d'),
        ),
        migrations.AddField(
            model_name='host',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x9e\x8b\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='host',
            name='node_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='host',
            name='powers',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe7\x94\xb5\xe6\xba\x90\xe6\x95\xb0\xe9\x87\x8f'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ip',
            field=models.GenericIPAddressField(null=True, unique=True, verbose_name=b'IP\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x9e\x8b\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='node_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='storage',
            name='ip',
            field=models.GenericIPAddressField(null=True, unique=True, verbose_name=b'IP\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AddField(
            model_name='storage',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x9e\x8b\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='storage',
            name='node_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
        migrations.AddField(
            model_name='storage',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AddField(
            model_name='storage',
            name='type',
            field=models.CharField(choices=[('switch', '\u4ea4\u6362\u673a'), ('firewall', '\u9632\u706b\u5899'), ('router', '\u8def\u7531\u5668'), ('server', '\u670d\u52a1\u5668'), ('storage', '\u5b58\u50a8'), ('ap', '\u65e0\u7ebfap')], max_length=20, null=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AddField(
            model_name='storage',
            name='vendor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe7\x94\x9f\xe4\xba\xa7\xe5\x8e\x82\xe5\x95\x86'),
        ),
        migrations.AlterField(
            model_name='host',
            name='be_from',
            field=models.CharField(blank=True, max_length=20, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe6\x9d\xa5\xe6\xba\x90'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cabinet',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.IDC', to_field=b'name', verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe4\xb8\xad\xe5\xbf\x83'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.IndustryGroup', verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe5\xbd\x92\xe5\xb1\x9e'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sys_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Contact', verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98'),
        ),
        migrations.AlterField(
            model_name='host',
            name='type',
            field=models.CharField(choices=[('switch', '\u4ea4\u6362\u673a'), ('firewall', '\u9632\u706b\u5899'), ('router', '\u8def\u7531\u5668'), ('server', '\u670d\u52a1\u5668'), ('storage', '\u5b58\u50a8'), ('ap', '\u65e0\u7ebfap')], max_length=20, null=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='host',
            name='unit_end',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\xb6\xe7\xbb\x93\xe6\x9d\x9f\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='host',
            name='unit_start',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\xb6\xe8\xb5\xb7\xe5\xa7\x8b\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vendor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe7\x94\x9f\xe4\xba\xa7\xe5\x8e\x82\xe5\x95\x86'),
        ),
        migrations.AlterField(
            model_name='host',
            name='zone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe5\x8c\xba\xe5\x9f\x9f'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='be_from',
            field=models.CharField(blank=True, max_length=20, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe6\x9d\xa5\xe6\xba\x90'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='cabinet',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.IDC', to_field=b'name', verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe4\xb8\xad\xe5\xbf\x83'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='local_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_admin', to='asset.Contact', to_field=b'name', verbose_name=b'\xe6\x9c\xac\xe5\x9c\xb0\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='maintenance_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Maintenance', to_field=b'maintenance_name', verbose_name=b'\xe7\xbb\xb4\xe4\xbf\x9d\xe5\x8d\x95\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.IndustryGroup', verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe5\xbd\x92\xe5\xb1\x9e'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='sn',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name=b'SN\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe7\x8a\xb6\xe6\x80\x81'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='sys_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Contact', verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='type',
            field=models.CharField(choices=[('switch', '\u4ea4\u6362\u673a'), ('firewall', '\u9632\u706b\u5899'), ('router', '\u8def\u7531\u5668'), ('server', '\u670d\u52a1\u5668'), ('storage', '\u5b58\u50a8'), ('ap', '\u65e0\u7ebfap')], max_length=20, null=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='unit_end',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\xb6\xe7\xbb\x93\xe6\x9d\x9f\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='unit_start',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\xb6\xe8\xb5\xb7\xe5\xa7\x8b\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='vendor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe7\x94\x9f\xe4\xba\xa7\xe5\x8e\x82\xe5\x95\x86'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='zone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe5\x8c\xba\xe5\x9f\x9f'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='be_from',
            field=models.CharField(blank=True, max_length=20, verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe6\x9d\xa5\xe6\xba\x90'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='cabinet',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='contract',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe9\x87\x87\xe8\xb4\xad\xe5\x90\x88\xe5\x90\x8c'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.IDC', to_field=b'name', verbose_name=b'\xe6\x95\xb0\xe6\x8d\xae\xe4\xb8\xad\xe5\xbf\x83'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='maintenance_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Maintenance', to_field=b'maintenance_name', verbose_name=b'\xe7\xbb\xb4\xe4\xbf\x9d\xe5\x8d\x95\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.IndustryGroup', verbose_name=b'\xe8\xb5\x84\xe4\xba\xa7\xe5\xbd\x92\xe5\xb1\x9e'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='sn',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name=b'SN\xe5\x8f\xb7'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='unit_end',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\xb6\xe7\xbb\x93\xe6\x9d\x9f\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='unit_start',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9e\xb6\xe8\xb5\xb7\xe5\xa7\x8b\xe4\xbd\x8d'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='zone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe6\x9c\xba\xe6\x9f\x9c\xe5\x8c\xba\xe5\x9f\x9f'),
        ),
        migrations.AddField(
            model_name='storage',
            name='sys_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Contact', verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xae\xa1\xe7\x90\x86\xe5\x91\x98'),
        ),
    ]
